on:
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Go Setup
        uses: actions/setup-go@v5
        with:
          go-version: stable
      - name: Vet
        run: |
          go vet -v ./...
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.1

  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Go Setup
        uses: actions/setup-go@v5
        with:
          go-version: stable
      - name: Unit Test
        run: |
          go test -v -test.v -race -cover -short -timeout 1m ./...

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Go Setup
        uses: actions/setup-go@v5
        with:
          go-version: stable
      - name: Build Binary
        run: |
          go build .
      - name: Build Container
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false